/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InvoiceRouteImport } from './routes/invoice'
import { Route as RecordsRouteImport } from './routes/records'

const InvoiceRoute = InvoiceRouteImport.update({
  id: '/invoice',
  path: '/invoice',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsRoute = RecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/invoice': typeof InvoiceRoute
  '/records': typeof RecordsRoute
}
export interface FileRoutesByTo {
  '/invoice': typeof InvoiceRoute
  '/records': typeof RecordsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/invoice': typeof InvoiceRoute
  '/records': typeof RecordsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/invoice' | '/records'
  fileRoutesByTo: FileRoutesByTo
  to: '/invoice' | '/records'
  id: '__root__' | '/invoice' | '/records'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  InvoiceRoute: typeof InvoiceRoute
  RecordsRoute: typeof RecordsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/invoice': {
      id: '/invoice'
      path: '/invoice'
      fullPath: '/invoice'
      preLoaderRoute: typeof InvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records': {
      id: '/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof RecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  InvoiceRoute: InvoiceRoute,
  RecordsRoute: RecordsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
